store1project/store/urls.py
from .import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


app_name = 'Store'
urlpatterns = [
    path('', views.store, name='store'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('order/', views.order, name='order'),
    path('logout/', views.logout, name='logout'),
    path('confirm_order', views.conf_order, name='conf_order')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store1project/store1project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
]

store1project/store/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.db.models.deletion import CASCADE


# Create your models here.
class Department(models.Model):
    departmentname = models.CharField(max_length=250)

    def __str__(self):
        return self.departmentname


class Course(models.Model):
    deptid = models.ForeignKey(Department, on_delete=CASCADE)
    course = models.CharField(max_length=250)

    def __str__(self):
        return self.course


class Order(models.Model):
    name = models.CharField(max_length=200)
    dob = models.DateField(default=None)
    age = models.IntegerField(default=None)
    gender = models.CharField(max_length=50, choices=(('Male', 'Male'), ('Female', 'Female'),))
    phone = models.CharField(max_length=10, default=None)
    email = models.EmailField()
    address = models.TextField(max_length=250)
    department = models.CharField(max_length=50)
    course = models.CharField(max_length=50)
    purpose = models.CharField(max_length=50)
    material = models.CharField(max_length=50)

    def __str__(self):
        return self.name

store1project/store/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import messages, auth
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Department, Course, Order



# Create your views here.
def store(request):
    return render(request, 'home.html')


def register(request):
    if request.method == 'POST':
        user_name = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        conf_password = request.POST['password1']

        if password == conf_password:
            if User.objects.filter(username=user_name).exists():
                messages.info(request, 'Username Already Taken')
                return redirect('Store:register')

            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email Already Taken')
                return redirect('Store:register')

            else:
                user = User.objects.create_user(
                    username=user_name, first_name=first_name, last_name=last_name,
                    password=password, email=email
                )
                user.save()
                messages.info(request, 'Welcome')
        else:
            messages.info(request, 'Password not matched')
            return redirect('Store:register')

        return redirect('Store:login')

    return render(request, 'register.html')


def login(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('Store:order')
        else:
            messages.info(request, 'Invalid Credential')
            return redirect('Store:login')
    return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')


def order(request):
    return render(request, 'order.html')


def conf_order(request):
    if request.method == 'POST':
        name = request.POST['name']
        dob = request.POST['dob']
        age = request.POST['age']
        gender = request.POST['gender']
        phone = request.POST['phone']
        email = request.POST['email']
        address = request.POST['address']
        department = request.POST['department']
        department = Department.objects.get(id=department)
        course = request.POST['course']
        course = Course.objects.get(id=course)
        purpose = request.POST['purpose']
        material = request.POST.getlist('material[]')
        orders = Order(
            name=name,
            dob=dob,
            age=age,
            gender=gender,
            phone=phone,
            email=email,
            address=address,
            department=department,
            course=course,
            purpose=purpose,
            material=material
        )
        orders.save()
        messages.info(request, 'Successfully Regestered...!!')

    depts = Department.objects.all()
    course = Course.objects.all()
    return render(request, 'conforder.html', {'depts': depts, 'courses': course, })

store1project/templates/conforder.html
{% extends 'home.html' %}
{% block content %}

<section class="h-100 h-custom gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px;">
          <form method="post">
            {% csrf_token %}
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="p-5">
                  <h3 class="fw-normal mb-5" style="color: #6600cc;">DETAILS</h3>

                  <div class="col-md-12 mb-4 pb-1">
                    <div class="form-outline">
                      <input type="text" id="form3Examplev2" name="name" class="form-control form-control-lg" placeholder="Name" required/>
                    </div>
                  </div>

                  <div class="mb-4 pb-2">
                    <div class="form-outline">
                      <input type="date" id="form3Examplev4" name="dob" class="form-control form-control-lg"  placeholder="DOB" required/>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-6 mb-4 pb-2 ">
                      <div class="form-outline">
                        <input type="number" name="age" class="form-control form-control-lg" placeholder="Age"/>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="row" style="padding-left:10px" >
                        <div class="form-check form-check-inline">
                          <input class="form-check-input" type="radio" name="gender" id="inlineCheckbox1" value="Male" required>
                          <label class="form-check-label" for="inlineCheckbox1">Male</label>
                        </div>
                        <div class="form-check form-check-inline">
                          <input class="form-check-input" type="radio" name="gender" id="inlineCheckbox2" value="Female" required>
                          <label class="form-check-label" for="inlineCheckbox2">Female</label>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="mb-4 pb-2  ">
                    <div class="form-outline">
                      <input type="tel" name="phone" class="form-control form-control-lg"  placeholder="Phone Number"/>
                    </div>
                  </div>

                  <div class="mb-4 pb-2 ">
                    <div class="form-outline">
                      <input type="email" name="email" class="form-control form-control-lg"  placeholder="Email"/>
                    </div>
                  </div>

                  <div class="mb-4 pb-2 mb-md-0 pb-md-0">
                    <div class="form-outline">
                      <textarea name="address" class="form-control form-control-lg"  placeholder="Address"></textarea>
                    </div>
                  </div>
                </div>
              </div>


              <div class="col-lg-6 bg-tomato text-black">
                <div class="p-5 mb-5">
                  <h3 class="fw-normal mb-5">Course Details</h3>

                  <div class="mb-4 pb-2">
                    <div class="dropdown">
                    <select  id="select1" class="form-select" name="department" required>
                      <option selected disabled="true">Department</option>
                      {% for dept in depts %}
                      <option value="{{dept.id}} ">{{dept.departmentname}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  </div>

                  <div class="mb-4 pb-2">
                      <select id="select2" class="form-select form-control-lg" name="course" required>
                        {% for course in courses %}
                        <option value="{{course.deptid_id}} " >{{ course.course}}</option>
                        {% endfor %}
                      </select>
                  </div>

                  <div class="mb-4 pb-2">
                    <select id="select3" class="form-select" name="purpose" required>
                      <option selected disabled="true">Purpose</option>
                      <option value="Enquiry">Enquiry</option>
                      <option value="Purchase">Verification</option>
                      <option value="Return">General View</option>
                    </select>
                </div>

                  <div class="row">
                    <div class="col-md-4">
                      Material Provided:
                    </div>

                    <div class="col-md-8">
                      <div class="mb-4 pb-2">
                        <div class="row">
                          <div class="col-md-5">
                            <div class="form-check form-switch">
                              <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" name="material[]" value="Pen">
                              <label class="form-check-label" for="flexSwitchCheckDefault">Pen</label>
                            </div>
                          </div>

                          <div  class="col-md-5">
                            <div class="form-check form-switch">
                              <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" name="material[]" value="Notebook">
                              <label class="form-check-label" for="flexSwitchCheckDefault2">PrintedNotes</label>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="mb-4 pb-2">
                        <div class="row">
                          <div class="col-md-5 ">
                            <div class="form-check form-switch">
                              <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault3" name="material[]" value="Instrument">
                              <label class="form-check-label" for="flexSwitchCheckDefault3">Reffering Materials</label>
                            </div>
                          </div>

                          <div  class="col-md-5">
                            <div class="form-check form-switch">
                              <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault4" name="material[]" value="Pencil">
                              <label class="form-check-label" for="flexSwitchCheckDefault4">Pencil</label>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <button type="submit" value="submit" name="submit"
                          style="font:18pt Helvetica; background:green;">Submit </button>



                  <div class="mb-4 pb-2 mb-md-0 pb-md-0">
                    <div class="form-outline">
                      {% for msg in messages %}
                      <div class="alert alert-success">
                        <p style="tomato">
                        <strong>{{msg}}</strong> <a href="{% url 'Store:store' %}" class="alert-link">Return To Home Page </a></div>
                     </p>
                      {% endfor %}
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>



<script>
  $(document).ready(function()
  {
    var $select1=$('#select1'),
        $select2=$('#select2'),
        $options=$select2.find('option');
        $select1.on('change',function()
        {
          $select2.html($options.filter('[value="'+ this.value + '"]'));
        }).trigger('change');
  });
</script>

<script>
  $(document).ready(function()
  {
    // $('#select1').select2();
    // $('#select2').select2();


  });
</script>
{% endblock %}

store1project/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link href="{% static 'custom.css' %}" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  <title>College Store</title>

</head>
{% if user.is_authenticated %}


<body style="background-image:url('img_background.jpg');background-size:100% 100%;background-repeat:no-repeat;">
{% else %}
<body>
{% endif %}

 <center>
<img src="{% static 'img/logo.png' %}" alt="logimage" width="100px;" > </center></div>



<div class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <div class="container-fluid ">

      <div class="collapse navbar-collapse" id="navbarScroll">
        <h class="nav-link" style="color:#0000CD;font-size:18px;" aria-current="page" href=""><b> WELCOME TO A.J SCHOOL SITE</b></h>

        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll"></ul>


        <div class="d-flex">
          <div class="dropdown" style="color:#191970;">

            <a class="nav-link dropdown-toggle active" href="" id="navbarScrollingDropdown"
               role="button" data-bs-toggle="dropdown" aria-expanded="false">DEPARTNMENT</a>

            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarScrollingDropdown">
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/artssubject">ARTS-STREAM</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/sciencefield">SCIENCE-STREAM</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/commercefield">COMMERCE</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/medicalfield">MEDICINE</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/engineeringfield"> ENGINEERING</a></li>
            </ul>

          </div>


          <div class="dropdown" style="margin:auto;">
            <a
                    class="dropdown-toggle d-flex align-items-center hidden-arrow"
                    href=""
                    id="navbarDropdownMenuAvatar"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false">

              {% if user.is_authenticated %}
              <img
                    src="https://i.stack.imgur.com/dr5qp.jpg"
                    class="rounded-circle"
                    height="25"
                    alt="D user"
                    loading="lazy" />
              {% else %}
             <img
                     src="https://as2.ftcdn.net/v2/jpg/02/15/84/43/1000_F_215844325_ttX9YiIIyeaR7Ne6EaLLjMAmy4GvPC69.jpg"
                     class="rounded-circle"
                     height="25"
                     alt="D user"
                     loading="lazy" />
              {% endif %}</a>


            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
              {% if user.is_authenticated %}
              <li><a class="dropdown-item disabled" style="color:teal;">{{user.username}}</a></li>
              <li><a class="dropdown-item" href="{% url 'Store:logout' %}">Log out</a></li>
              <li><a class="dropdown-item" href="{% url 'Store:order' %}">order</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'Store:login' %}">Sign In</a></li>
              <li><a class="dropdown-item" href="{% url 'Store:register' %}">Register</a></li>
              {% endif %}
            </ul>

          </div>
        </div>
      </div>
    </div>
  </nav>
</div>


</div>
</body>
</body>
</html>
{% block content %}
{% endblock %}

store1project/templates/login.html
{% extends 'home.html' %}

{% block content %}
{% load static %}

<section class="vh-100">

  <div class=" container py-5 h-50">
   <div class="row d-flex justify-content-center align-items-center h-100">
     <div class=" col col-xl-6" style="">
       <div class="card" style="box-shadow: 0 8px 20px 0px #800000;border-radius: 1px;">
          <div class="row g-0">
            <div class="col-sm-2"></div>
              <div class="col-sm-8 align-items-center">
                <div class="card-body p-1 p-lg-2 text-black">

                  <form  method="post" >
                    {% csrf_token %}
                    <div align="center">
                      <p style="#FFC0CB" >
                      <h1 class="heading-name h1 fw-bold mb-0 " >A.J Schools</h1></h>
                      </p>
                    </div>
                    <div align="center">
                    <h1 class="fw-normal mb-3 pb-3 text-muted" style="letter-spacing: 2px;">SignIn</h1>
                    </div>
                    <div class="form-outline mb-4">
                        <div align="center">
                      <p>
                      <input type="text" id="form2Example17" class="form-control form-control-lg" name="username" placeholder="Username" />
                   </p>
                            </div>
                    </div>


                    <div class="form-outline mb-4">
                        <div align="center">
                      <input type="password" id="form2Example27" class="form-control form-control-lg" name="password" placeholder="Password"/>
                    </div>
                    </div>
                  <p>
                    <div class="pt-1 mb-4">
                    <div align="center">
                      <button class="col-sm-12 btn btn-dark btn-lg btn-block" type="submit" style="font:18pt Helvetica; background:green">Login</button>
                    </p>

                    </div></div>
                        <div align="center">

                    <p class="small text-center" style="color: #393f81;">Don't have an account?
                      <a href="{% url 'Store:register' %}" style="color: lime;text-decoration:none">Register here</a>
                    </p>
                        </div>
                    {% for msg1 in messages %}
                    <div class="alert alert-primary" role="alert">
                      {{msg1}}
                    </div>
                    {% endfor %}

                  </form>
                </div>
              </div>
            <div class="col-sm-2 col-lg-7 d-flex align-items-center"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

store1project/templates/order.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<body bgcolor="#B0E0E6">
<section class="">
  <div class=" ">

    <div align="center" ><h2 style="color:indigo;">WELCOME TO A.J SCHOOLS</h2></div>
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class=" col col-xl-5" style="">
        <a href="{% url 'Store:conf_order' %}" style="text-decoration:none">

<p align="center">
          <div align="center">
          <button type="button" class="btn btn-primary btn-lg" style="background: lime;font:18pt Helvetica"> SignIn </button>

<!--          <div class="button" style="box-shadow: 0 8px 10px 0px #00FA9A;border-radius: 105px;">-->
<!--        </p><h2>SignIn</h2>-->
<!--          </div>-->
        </a>
      </div>
    </div>
  </div>
</section>
</body>
{% endif %}
{% endblock %}

store1project/templates/register.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<body bgcolor="teal;" >
<div>
<!--    <center>-->
<!--<img src="{% static 'img/logo.png' %}" alt="logimage" width="100px;" > </center></div>-->
<div align="center"><h1>REGISTRATION FORM</h1></div>


<div class="wrapper" >
        <div class="form-left">
            <h2 class="text-uppercase">A.J Schools</h2>

            <p class="text" >
                <div class="center">
                <span> Sign IN</span>
            </p>
            </div>
            <div class="form-field">
                <a href="{% url 'Store:login' %}"><input type="submit" class="account" value="SignIn"></a>
            </div>
            {% for msg1 in messages %}
            <div class="alert alert-primary" role="alert">
                {{msg1}}
            </div>
             {% endfor %}
        </div>
      </div>

        <form method="post" >
            {% csrf_token %}
            <div align="center"  ><h2 class="text-uppercase"></h2> </div>
            <div class="mb-3">
                <label>Username</label>
                <input type="text" class="input-field" name="username" required>
            </div>
            <div class="row">
                <div class="col-sm-6 mb-3">
                    <label>First Name</label>
                    <input type="text" name="first_name" id="first_name" class="input-field">
                </div>
                <div class="col-sm-6 mb-3">
                    <label>Last Name</label>
                    <input type="text" name="last_name" id="last_name" class="input-field">
                </div>
            </div>
            <div class="mb-3">
                <label>Your Email</label>
                <input type="email" class="input-field" name="email" required>
            </div>
            <div class="row">
                <div class="col-sm-6 mb-3">
                    <label>Password</label>
                    <input type="password" name="password" id="pwd" class="input-field">
                </div>
                <div class="col-sm-6 mb-3">
                    <label>Confirm password</label>
                    <input type="password" name="password1" id="cpwd" class="input-field">
                </div>
            </div>
            <div class="mb-3" align="center">
                <label class="option">I agree to the <a href="#">Terms and Conditions</a>
                    <input type="checkbox" checked>
                    <span class="checkmark"></span>
                </label>
            </div>
            <div class="form-field" align="center">

                <button type="submit" class="register" style="background:lime;">Register</button>
            </div>
        </form>
</body>
    </div>



{% endblock %}